name: CI
on:
    push:
    pull_request:
    schedule:
        - cron: '0 2 * * 0'

env:
    USE_RPATH: yes
    GOST_PROVIDER_ENABLE_ONLINE_TESTS: 1

jobs:
    gcc-provider-openssl-fork-tls13:
        runs-on: ubuntu-latest
        env:
            PATCH_OPENSSL: 1
            GOST_BUILD_ENGINE: OFF
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    clang-provider-openssl-fork-tls13:
        runs-on: ubuntu-latest
        env:
            CC: clang
            PATCH_OPENSSL: 1
            GOST_BUILD_ENGINE: OFF
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    macos-provider-openssl-fork-tls13:
        runs-on: macos-latest
        env:
            USE_RPATH:
            GOST_PROVIDER_ENABLE_ONLINE_TESTS: 0 # macOS runner has no network access to infotecs TLS1.3 server
            PATCH_OPENSSL: 1
            GOST_BUILD_ENGINE: OFF
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh
